name: indentsystem
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^4.2.1
  provider: ^6.0.1
  flutter_launcher_icons: ^0.9.2
  dio: ^4.0.0
  socket_io_client: ^2.0.1
  intl: ^0.18.0
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
#  firebase_core: ^2.8.0
#  firebase_analytics: ^10.1.6
#  firebase_messaging: ^14.3.0
#  firebase_core_web: ^2.2.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.1
  json_theme: ^5.0.2+3
  infinite_scroll_pagination: ^3.2.0
  photo_view: ^0.14.0
  dropdown_button2: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/tones/
    - assets/icons/
    - assets/images/

  # example:
  fonts:
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita_Regular.otf
        - asset: assets/fonts/Gordita_Medium.otf
        - asset: assets/fonts/Gordita_Light.otf
        - asset: assets/fonts/Gordita_Bold.otf
        - asset: assets/fonts/Gordita_Thin.otf
